[package]
name = "templify"
version = "0.2.0"
edition = "2021"
description = "File generation helper using a data dictionary and Jinja2 template files."
license = "MIT"
readme = "README.md"
repository = "https://github.com/robinbreast/templify"
keywords = ["jinja", "jinja2", "j2", "template", "generator"]
categories = ["template-engine"]

[[bin]]
name = "yagen"
path = "src/main.rs"

[[bin]]
name = "manual-sections"
path = "src/bin/manual-sections.rs"


[dependencies]
minijinja = { version = "=2.14.0", features = ["custom_syntax"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.5.4"
log = "0.4"
clap = { version = "4.4", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"
thiserror = "1.0"
env_logger = "0.11"
heck = "0.5"
uuid = { version = "1.10", features = ["v4", "v5", "fast-rng", "macro-diagnostics"] }
toml = "0.8"
chrono = { version = "0.4", features = ["clock"] }
humansize = "2"
md5 = "0.7"
sha2 = "0.10"
base64 = "0.22"
rand = "0.8"
num-format = "0.4"
jsonschema = "0.17"
walkdir = "2.4"
glob = "0.3.3"

[dev-dependencies]
tempfile = "3.2"
fs_extra = "1"
